BEGIN;

CREATE TABLE IF NOT EXISTS public.indicators (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol text NOT NULL,
  name text NOT NULL,
  category text NOT NULL,
  value double precision NOT NULL,
  previous_value double precision NOT NULL,
  value_unit text NOT NULL DEFAULT '',
  change_type text NOT NULL,
  source text NOT NULL,
  as_of date NOT NULL,
  frequency text NOT NULL,
  is_manual boolean NOT NULL DEFAULT false,
  is_featured boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT indicators_symbol_key UNIQUE (symbol),
  CONSTRAINT indicators_change_type_check
    CHECK (change_type IN ('bp', 'percent'))
);

CREATE INDEX IF NOT EXISTS indicators_category_sort_name_idx
  ON public.indicators (category, sort_order, name);

CREATE TABLE IF NOT EXISTS public.macro_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_time timestamp without time zone NOT NULL,
  region text NOT NULL,
  name text NOT NULL,
  importance integer NOT NULL DEFAULT 3,
  previous text,
  forecast text,
  actual text,
  source text NOT NULL,
  is_manual boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT macro_events_importance_check
    CHECK (importance BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS macro_events_event_time_idx
  ON public.macro_events (event_time);

COMMIT;
