-- Production Trading Journal schema and RLS transaction body.
-- The Production migration runner owns BEGIN/COMMIT and only executes this
-- body after classifying the database as table-absent or legacy-empty.

DO $create_table$
BEGIN
IF to_regclass('public.daily_market_notes') IS NULL THEN
CREATE TABLE public.daily_market_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  note_date date NOT NULL,
  thesis text NOT NULL,
  summary text NOT NULL,
  supporting_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  opposing_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  watchlist jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT daily_market_notes_user_date_key UNIQUE (user_id, note_date),
  CONSTRAINT daily_market_notes_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE RESTRICT,
  CONSTRAINT daily_market_notes_thesis_check CHECK (
    thesis IN ('流动性','货币政策','通胀','经济增长','风险偏好','地缘政治','财政','技术性因素','暂无明确主线')
  ),
  CONSTRAINT daily_market_notes_summary_length_check CHECK (
    char_length(summary) BETWEEN 1 AND 200
  ),
  CONSTRAINT daily_market_notes_supporting_array_check CHECK (
    jsonb_typeof(supporting_evidence) = 'array'
  ),
  CONSTRAINT daily_market_notes_opposing_array_check CHECK (
    jsonb_typeof(opposing_evidence) = 'array'
  ),
  CONSTRAINT daily_market_notes_watchlist_array_check CHECK (
    jsonb_typeof(watchlist) = 'array' AND jsonb_array_length(watchlist) <= 3
  )
);
END IF;
END
$create_table$;

-- The only upgradable legacy state is an empty, recognized v0.1 table.
ALTER TABLE public.daily_market_notes
  ADD COLUMN IF NOT EXISTS user_id uuid;

ALTER TABLE public.daily_market_notes
  ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE public.daily_market_notes
  DROP CONSTRAINT IF EXISTS daily_market_notes_note_date_key;

DO $drop_legacy_unique$
DECLARE
  target_table regclass := 'public.daily_market_notes'::regclass;
  note_date_attnum smallint;
  legacy_constraint record;
BEGIN
  SELECT attnum INTO note_date_attnum
    FROM pg_attribute
   WHERE attrelid=target_table AND attname='note_date' AND NOT attisdropped;

  FOR legacy_constraint IN
    SELECT conname FROM pg_constraint
     WHERE conrelid=target_table AND contype='u'
       AND conkey=ARRAY[note_date_attnum]::smallint[]
  LOOP
    EXECUTE format(
      'ALTER TABLE public.daily_market_notes DROP CONSTRAINT IF EXISTS %I',
      legacy_constraint.conname
    );
  END LOOP;
END
$drop_legacy_unique$;

DO $ensure_constraints$
DECLARE
  target_table regclass := 'public.daily_market_notes'::regclass;
  auth_table regclass := 'auth.users'::regclass;
  user_attnum smallint;
  date_attnum smallint;
  auth_id_attnum smallint;
  current_unique record;
  current_foreign_key record;
BEGIN
  SELECT attnum INTO user_attnum FROM pg_attribute
   WHERE attrelid=target_table AND attname='user_id' AND NOT attisdropped;
  SELECT attnum INTO date_attnum FROM pg_attribute
   WHERE attrelid=target_table AND attname='note_date' AND NOT attisdropped;
  SELECT attnum INTO auth_id_attnum FROM pg_attribute
   WHERE attrelid=auth_table AND attname='id' AND NOT attisdropped;

  SELECT contype, conkey INTO current_unique
    FROM pg_constraint
   WHERE conrelid=target_table AND conname='daily_market_notes_user_date_key';
  IF NOT FOUND THEN
    ALTER TABLE public.daily_market_notes
      ADD CONSTRAINT daily_market_notes_user_date_key UNIQUE (user_id, note_date);
  ELSIF current_unique.contype <> 'u'
     OR current_unique.conkey <> ARRAY[user_attnum, date_attnum]::smallint[] THEN
    RAISE EXCEPTION 'Unexpected daily_market_notes_user_date_key definition';
  END IF;

  SELECT contype, conkey, confrelid, confkey, confdeltype
    INTO current_foreign_key
    FROM pg_constraint
   WHERE conrelid=target_table AND conname='daily_market_notes_user_id_fkey';
  IF NOT FOUND THEN
    ALTER TABLE public.daily_market_notes
      ADD CONSTRAINT daily_market_notes_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES auth.users(id)
      ON DELETE RESTRICT NOT VALID;
  ELSIF current_foreign_key.contype <> 'f'
     OR current_foreign_key.conkey <> ARRAY[user_attnum]::smallint[]
     OR current_foreign_key.confrelid <> auth_table
     OR current_foreign_key.confkey <> ARRAY[auth_id_attnum]::smallint[]
     OR current_foreign_key.confdeltype <> 'r' THEN
    RAISE EXCEPTION 'Unexpected daily_market_notes_user_id_fkey definition';
  END IF;
END
$ensure_constraints$;

ALTER TABLE public.daily_market_notes
  VALIDATE CONSTRAINT daily_market_notes_user_id_fkey;

CREATE INDEX IF NOT EXISTS daily_market_notes_updated_at_idx
  ON public.daily_market_notes (updated_at DESC);

COMMENT ON COLUMN public.daily_market_notes.user_id IS
  'Supabase Auth user that owns this private Trading Journal entry.';

ALTER TABLE public.daily_market_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_market_notes FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS daily_market_notes_select_own ON public.daily_market_notes;
CREATE POLICY daily_market_notes_select_own
  ON public.daily_market_notes FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS daily_market_notes_insert_own ON public.daily_market_notes;
CREATE POLICY daily_market_notes_insert_own
  ON public.daily_market_notes FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS daily_market_notes_update_own ON public.daily_market_notes;
CREATE POLICY daily_market_notes_update_own
  ON public.daily_market_notes FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS daily_market_notes_delete_own ON public.daily_market_notes;
CREATE POLICY daily_market_notes_delete_own
  ON public.daily_market_notes FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

REVOKE ALL PRIVILEGES ON TABLE public.daily_market_notes FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public.daily_market_notes FROM authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.daily_market_notes FROM service_role;
REVOKE ALL PRIVILEGES ON TABLE public.daily_market_notes FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE public.daily_market_notes TO authenticated;

REVOKE ALL PRIVILEGES ON SEQUENCE public.daily_market_notes_id_seq FROM anon;
REVOKE ALL PRIVILEGES ON SEQUENCE public.daily_market_notes_id_seq FROM authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.daily_market_notes_id_seq FROM service_role;
REVOKE ALL PRIVILEGES ON SEQUENCE public.daily_market_notes_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.daily_market_notes_id_seq TO authenticated;
