BEGIN;

CREATE TABLE IF NOT EXISTS public.daily_market_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_date date NOT NULL,
  thesis text NOT NULL,
  summary text NOT NULL,
  supporting_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  opposing_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  watchlist jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT daily_market_notes_note_date_key UNIQUE (note_date),
  CONSTRAINT daily_market_notes_thesis_check CHECK (
    thesis IN ('流动性','货币政策','通胀','经济增长','风险偏好','地缘政治','财政','技术性因素','暂无明确主线')
  ),
  CONSTRAINT daily_market_notes_summary_length_check CHECK (
    char_length(summary) BETWEEN 1 AND 200
  ),
  CONSTRAINT daily_market_notes_supporting_array_check CHECK (
    jsonb_typeof(supporting_evidence) = 'array'
  ),
  CONSTRAINT daily_market_notes_opposing_array_check CHECK (
    jsonb_typeof(opposing_evidence) = 'array'
  ),
  CONSTRAINT daily_market_notes_watchlist_array_check CHECK (
    jsonb_typeof(watchlist) = 'array' AND jsonb_array_length(watchlist) <= 3
  )
);

CREATE INDEX IF NOT EXISTS daily_market_notes_updated_at_idx
  ON public.daily_market_notes (updated_at DESC);

COMMIT;
